Matth
MatthLC/P2_scrape_book pull request #11
Opened 2021-06-24 12:41 UTC by MatthLC

Correction des précédents retours

2021-06-24 13:19 UTC, williamsko requested changes
Tu laisses d'autres espaces entre les lignes de ton code.  Ne ferme surtout pas cette PR avant que le code ne soit validé.

Elimine les espaces inutiles entre les lignes.

2021-06-24 14:01 UTC, MatthLC commented
Aie désolé. Mais je peux appliquer des modifications sur cette PR ?

2021-06-24 14:04 UTC, williamsko commented
Oui oui

Le jeu. 24 juin 2021 à 16:01, MatthLC ***@***.***> a écrit :

> Aie désolé. Mais je peux appliquer des modifications sur cette PR ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/MatthLC/P2_scrape_book/pull/11#issuecomment-867661444>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2HYSLZJ4KU2M5SKT5FFWLTUM3FLANCNFSM47HZ7UFQ>
> .
>

2021-06-24 14:08 UTC, MatthLC commented
ok je viens de réaliser que mon dernier push a actualisé le PR :) je viens de mettre à jour

2021-06-25 12:27 UTC, MatthLC commented
Bonjour Williams,

Est-ce que je peux effectuer le merge ?

2021-06-25 12:35 UTC, williamsko commented
Je fais un dernier check

Le ven. 25 juin 2021 à 14:27, MatthLC ***@***.***> a écrit :

> Bonjour Williams,
>
> Est-ce que je peux effectuer le merge ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/MatthLC/P2_scrape_book/pull/11#issuecomment-868464074>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2HYSIXCSPVWPAGYGQA6VDTURY2JANCNFSM47HZ7UFQ>
> .
>

2021-06-25 12:35 UTC, williamsko approved these changes
LGTM

2021-06-25 12:35 UTC, williamsko commented
C'est bon

Le ven. 25 juin 2021 à 14:34, Williams de SOUZA ***@***.***> a
écrit :

> Je fais un dernier check
>
> Le ven. 25 juin 2021 à 14:27, MatthLC ***@***.***> a écrit :
>
>> Bonjour Williams,
>>
>> Est-ce que je peux effectuer le merge ?
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/MatthLC/P2_scrape_book/pull/11#issuecomment-868464074>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AA2HYSIXCSPVWPAGYGQA6VDTURY2JANCNFSM47HZ7UFQ>
>> .
>>
>

2021-06-25 12:36 UTC, williamsko commented
j'ai approuvé

Le ven. 25 juin 2021 à 14:35, Williams de SOUZA ***@***.***> a
écrit :

> C'est bon
>
> Le ven. 25 juin 2021 à 14:34, Williams de SOUZA ***@***.***>
> a écrit :
>
>> Je fais un dernier check
>>
>> Le ven. 25 juin 2021 à 14:27, MatthLC ***@***.***> a
>> écrit :
>>
>>> Bonjour Williams,
>>>
>>> Est-ce que je peux effectuer le merge ?
>>>
>>> —
>>> You are receiving this because you commented.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/MatthLC/P2_scrape_book/pull/11#issuecomment-868464074>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AA2HYSIXCSPVWPAGYGQA6VDTURY2JANCNFSM47HZ7UFQ>
>>> .
>>>
>>

2021-06-25 12:36 UTC, MatthLC commented
merci !

2021-06-25 12:38 UTC, merged

2021-06-25 12:53 UTC, williamsko commented
N'oublie pas de m'envoyer le livrable pour que je puisse jeter un coup
d'oeil.

Le ven. 25 juin 2021 à 14:37, MatthLC ***@***.***> a écrit :

> merci !
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/MatthLC/P2_scrape_book/pull/11#issuecomment-868469176>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2HYSLT4OZ5625E2K3HWSLTURZ6ZANCNFSM47HZ7UFQ>
> .
>